### ISSUE TITLE
Add MIDI + SF2 export function

### ISSUE THREAD

**Issue by jpmac26** [loveemu/saptapper#5]
Hello, I recently found a program called "gba_mus_riper" which allows you to extract music from GBA ROMs that use the Sappy engine as MIDI files with related SF2 soundfonts, which allows you to listen to the music in a far higher quality than is possible with real hardware or emulation, because the music doesn't have to be butchered by the GBA's direct sound resampling. However, this program only works on some of the GBA games that use Sappy, and I know that your program can interpret several different GBA music formats. Therefore, would it be possible to allow this program to export MIDIs and SF2s as well as GSFs? Or better yet, convert GSFs to MIDIs and SF2s, because there are so many GSFs out there that were manually ripped. Anyway, thanks for any response/feedback!

**Comment by loveemu** [comment]
Saptapper is just for GSF ripping. So I obviously will not add MIDI+SF2 extraction. They are different functions.

[VGMTrans](https://github.com/vgmtrans/vgmtrans) is the software for MIDI+SF2 extraction. However it does not support GBA games well at present. Also I do not have an enough motivation on it.
